apiVersion: v1
kind: Service
metadata:
  name: bid-eval-nginx
spec:
  type: LoadBalancer
  selector:
    app: bid-eval-nginx
  ports:
    - port: 80
      targetPort: 80
    - port: 443
      targetPort: 443
