apiVersion: v1
kind: Service
metadata:
  name: {{ include "bidplatform-backend.fullname" . }}
spec:
  selector:
    app: {{ include "bidplatform-backend.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 4000
      protocol: TCP
      name: http
