apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bidplatform-backend
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: bidplatform.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bidplatform-backend
                port:
                  number: 80
