apiVersion: v1
kind: Service
metadata:
  name: bidplatform-backend
  labels:
    app: bidplatform-backend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/health/metrics"
    prometheus.io/port: "4000"
spec:
  selector:
    app: bidplatform-backend
  ports:
    - name: http
      port: 80
      targetPort: 4000
  type: ClusterIP
