apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bid-eval-backend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: bid-eval.local
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: bid-eval-backend
                port:
                  number: 80
