apiVersion: apps/v1
kind: Deployment
metadata:
  name: eval-frontend-public
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eval-frontend-public
  template:
    metadata:
      labels:
        app: eval-frontend-public
    spec:
      containers:
        - name: frontend-public
          image: zuzakami/eval-frontend-public:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: eval-config
