apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eval-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: api.zuzakami.co.za
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: eval-backend
                port:
                  number: 3000

    - host: verify.zuzakami.co.za
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: eval-frontend-public
                port:
                  number: 3000
