apiVersion: v1
kind: Secret
metadata:
  name: eval-secrets
type: Opaque
stringData:
  JWT_SECRET: "REPLACE_WITH_64_CHAR_RANDOM"
  EVAL_VERIFY_SECRET: "REPLACE_WITH_64_CHAR_RANDOM"
  DB_PASSWORD: "REPLACE_DB_PASSWORD"
